repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-astro@^0.12.3
        files: \.(astro|mdx|md|yml|yaml|ts|js|mjs)$
