[build]
  publish = "output/"
  command = "npm run build"

[build.environment]
    NODE_VERSION = "20.11.0"

[[redirects]]
  from = "/vscode"
  to = "https://marketplace.visualstudio.com/items?itemName=nextflow.nextflow"

[[redirects]]
  from = "/openvsx"
  to = "https://open-vsx.org/extension/nextflow/nextflow"

[[redirects]]
  from = "/presentations"
  to = "https://www.youtube.com/playlist?list=PLPZ8WHdZGxmVGS6VoiqDeZ3Q_tjw3aIbW"
