[build]
  publish = "output/"
  command = "npm run build"

[build.environment]
    NODE_VERSION = "20.11.0"

[[redirects]]
  from = "/vscode"
  to = "https://marketplace.visualstudio.com/items?itemName=nextflow.nextflow"

[[redirects]]
  from = "/openvsx"
  to = "https://open-vsx.org/extension/nextflow/nextflow"

[[redirects]]
  from = "/presentations"
  to = "https://www.youtube.com/playlist?list=PLPZ8WHdZGxmVGS6VoiqDeZ3Q_tjw3aIbW"

[[redirects]]
  from = "/presentations.html"
  to = "https://www.youtube.com/playlist?list=PLPZ8WHdZGxmVGS6VoiqDeZ3Q_tjw3aIbW"

[[redirects]]
  from = "/example1.html"
  to = "/basic-pipeline.html"

[[redirects]]
  from = "/example2.html"
  to = "/mixing-scripting-languages.html"

[[redirects]]
  from = "/example3.html"
  to = "/blast-pipeline.html"

[[redirects]]
  from = "/example4.html"
  to = "/rna-seq-pipeline.html"

[[redirects]]
  from = "/example5.html"
  to = "/machine-learning-pipeline.html"