[build]
  publish = "output/"
  command = "npm run build"

[build.environment]
    NODE_VERSION = "20.11.0"

[[redirects]]
  from = "/vscode"
  to = "https://marketplace.visualstudio.com/items?itemName=nextflow.nextflow"

[[redirects]]
  from = "/openvsx"
  to = "https://open-vsx.org/extension/nextflow/nextflow"

[[redirects]]
  from = "/presentations"
  to = "https://www.youtube.com/playlist?list=PLPZ8WHdZGxmVGS6VoiqDeZ3Q_tjw3aIbW"

[[redirects]]
  from = "/presentations.html"
  to = "https://www.youtube.com/playlist?list=PLPZ8WHdZGxmVGS6VoiqDeZ3Q_tjw3aIbW"

[[redirects]]
  from = "/example1.html"
  to = "/examples/basic-pipeline"

[[redirects]]
  from = "/example2.html"
  to = "/examples/mixing-scripting-languages"

[[redirects]]
  from = "/example3.html"
  to = "/examples/blast-pipeline"

[[redirects]]
  from = "/example4.html"
  to = "/examples/rna-seq-pipeline"

[[redirects]]
  from = "/example5.html"
  to = "/examples/machine-learning-pipeline"

# Direct redirects from old .html files to new structure
[[redirects]]
  from = "/basic-pipeline.html"
  to = "/examples/basic-pipeline"

[[redirects]]
  from = "/mixing-scripting-languages.html"
  to = "/examples/mixing-scripting-languages"

[[redirects]]
  from = "/blast-pipeline.html"
  to = "/examples/blast-pipeline"

[[redirects]]
  from = "/rna-seq-pipeline.html"
  to = "/examples/rna-seq-pipeline"

[[redirects]]
  from = "/machine-learning-pipeline.html"
  to = "/examples/machine-learning-pipeline"